[server]
http_port = 80
https_port = 443
http_enabled = true
https_enabled = true
behind_proxy = false

[registry]
upstream_registry = "https://registry-1.docker.io"
# Registry mapping configuration allows for redirecting requests to different registries
# Format: source_registry = "target_registry"
# Example: when you run `docker pull docxy.example.com/ghcr.io/binarization/something:latest`
# it will pull from `ghcr.io/binarization/something:latest`
[registry.registry_mapping]
"ghcr.io" = "https://ghcr.io"
"docker.io" = "https://registry-1.docker.io"

[tls]
cert_path = "/root/.acme.sh/example.com_ecc/fullchain.cer"
key_path = "/root/.acme.sh/example.com_ecc/example.com.key"
